[project]
name = "models-for-i"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gguf[gui]>=0.17.1",
    "huggingface-hub>=0.30.1",
]
